### ISSUE TITLE
Support TLS for MQTT connection

### ISSUE THREAD

**Issue by tobru** [Scrin/ruuvi-go-gateway#1]
It would be cool if TLS connections for MQTT would be possible for running it over insecure (aka the Internet) networks.

**Comment by Scrin** [comment]
This should be supported now, although I don't have any MQTT servers with TLS capability at the moment so I can't test it. I'd appreciate if you could give the latest version (which I've just published) a go and let me know if it works. The mqtt configuration changed a little, it now uses a `broker_url` which allows configuring the full url, including scheme (ssl:// for encrypted connections).

**Comment by tobru** [comment]
I can confirm that TLS connections to Mosquitto works with v0.1.4, thank you very much.
