### ISSUE TITLE
Configuration option for Bluetooth device

### ISSUE THREAD

**Issue by tobru** [Scrin/ruuvi-go-gateway#2]
The BLE scanner uses the system default device (https://github.com/Scrin/ruuvi-go-gateway/blob/master/gateway/gateway.go#L35).

In my case I have multiple bluetooth adapters and would like to configure which adapter to use for the gateway:

```
# hcitool dev
Devices:
        hci0    XX:XX:XX:XX:XX:XX
        hci1    YY:YY:YY:YY:YY:YY
```

**Comment by Scrin** [comment]
This is now supported in v0.1.5 and later via the new `hci_index` configuration option (see the sample config)

**Comment by tobru** [comment]
WOW, fantastic! Thank you very much :rocket:
