### ISSUE TITLE
Doesn't work with bookworm RPI3

### ISSUE THREAD

**Issue by Aketzu** [Scrin/ruuvi-go-gateway#9]
I tested ruuvi-go-gateway with Debian 11 (bullseye), everything worked and then updated to Debian 12 (bookworm). hcitool/hcidump worked nicely but ruuvi-go-gateway didn't see any tags

dmesg contains
```
[ 1900.676659] Bluetooth: hci0: Opcode 0x c03 failed: -4
[ 1900.681386] Bluetooth: hci0: unexpected event for opcode 0x0c03
```

I managed to fix this by changing from go-ble/ble to rigado/ble and adding LEScanInterval + LEScanWindow:
```go
  device, err := dev.NewDevice("default",
    ble.OptDeviceID(config.HciIndex),
    ble.OptScanParams(cmd.LESetScanParameters{
      LEScanType: 0, // passive scan
      LEScanInterval: 0x10,
      LEScanWindow: 0x10,
    }))
```

I guess go-ble doesn't validate those params and zero isn't working anymore.

**Comment by Scrin** [comment]
Fixed in #11
